class CreateDocuments < ActiveRecord::Migration
  def change
    create_table :documents do |t|
      t.string :document_name   # The name of the document, which shall be generated by the program
      t.integer :document_year   # The year of the document
      t.integer :term   # 1st, 2nd or 3rd
      t.integer :grade  # 1-6 => Primary, 7-12 => Secondary, 13-16 => Teritary
      t.string :document_location   # Update after assigning document

      t.timestamps
    end
  end
end
